services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:3.11.2
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/ddclient:/config
    restart: unless-stopped
