services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - nas
networks:
  nas:
    external: true
