networks:
  nas:
    external: true
  gitea:

services:
  gitea:
    image: gitea/gitea:1.22.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
      - nas
    volumes:
      - /data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitea.rule=Host(`gitea.fgdou.ovh`)'
      - 'traefik.http.routers.gitea.entryPoints=websecure'
      - 'traefik.http.services.gitea.loadbalancer.server.port=3000'
      - 'traefik.tcp.routers.gitea.entrypoints=ssh'
      - 'traefik.tcp.routers.gitea.rule=HostSNI(`*`)'
      - 'traefik.tcp.services.gitea.loadbalancer.server.port=22'
  gitea_runner:
    image: gitea/act_runner:nightly
    restart: always
    networks:
      - gitea
    environment:
      GITEA_INSTANCE_URL: "https://gitea.fgdou.ovh"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${GITEA_REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "Runner1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
