networks:
  nas:
    external: true

services:
  gitea:
    image: gitea/gitea:1.22.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - nas
    volumes:
      - /data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitea.rule=Host(`gitea.fgdou.ovh`)'
      - 'traefik.http.routers.gitea.entryPoints=websecure'
      - 'traefik.http.services.gitea.loadbalancer.server.port=3000'
      - 'traefik.tcp.routers.gitea.entrypoints=ssh'
      - 'traefik.tcp.routers.gitea.rule=HostSNI(`*`)'
      - 'traefik.tcp.services.gitea.loadbalancer.server.port=22'
