version: '2'
services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: homeassistant/home-assistant:2024.4
    volumes:
      - /data/Homeassistant/core:/config
      - /etc/localtime:/etc/localtime:ro
      - /data/Homeassistant/media:/media
      - /run/dbus:/run/dbus
    restart: unless-stopped
    privileged: true
    network_mode: host
    #ports:
    #  - 8123:8123
    user: "root:users"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
  nodered:
    image: nodered/node-red:3.1
    user: "root:users"
    restart: unless-stopped
    hostname: nodered
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - nas
    volumes:
      - /data/Homeassistant/nodered:/data
    depends_on:
      - homeassistant

networks:
  nas:
    external: true
