version: "3.9"

services:
  ihatemoney:
    image: ihatemoney/ihatemoney:latest
    container_name: ihatemoney
    environment:
      - PORT=8000
      - PUID=0
      - PGID=0
      - ACTIVATE_ADMIN_DASHBOARD=True
      - ADMIN_PASSWORD=${IHATEMONEY_ADMIN_PASSWORD}
      - ALLOW_PUBLIC_PROJECT_CREATION=False
    volumes:
      - /data/ihatemoney:/database
    restart: unless-stopped
    networks:
      - nas
networks:
  nas:
    external: true
