version: "3"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.3.2
    container_name: mealie
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /data/maelie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.fgdou.ovh
      - SMTP_HOST=mail.fgdou.ovh
      - SMTP_FROM_EMAIL=no-reply@fgdou.ovh
      - SMTP_USER=no-reply@fgdou.ovh
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTH_STRATEGY=TLS
    restart: always
    networks:
      - nas

networks:
  nas:
    external: true
