services:
  nextcloud:
    networks:
      - nas
      - nextcloud
    image: nextcloud:29.0.3
    volumes:
      - /data/nextcloud/code:/var/www/html
    environment:
      - APACHE_DISABLE_REWRITE_IP=true
      - TRUSTED_PROXIES=10.0.0.0/8 172.16.0.0/12
      - OVERWRITEHOST=nextcloud.fgdou.ovh
      - OVERWRITEPROTOCOL=https
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
    depends_on:
      - db
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.rule=Host(`nextcloud.fgdou.ovh`)'
      - 'traefik.http.routers.nextcloud.entryPoints=websecure'
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'
  db:
    image: postgres:16.1
    container_name: nextcloud_db
    volumes:
      - /data/nextcloud/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=nextcloud
    networks:
      - nextcloud
    restart: unless-stopped

networks:
  nas:
    external: true
  nextcloud:
