version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:2.11.1'
    restart: unless-stopped
    ports:
      - '80:80'
      - '82:81'
      - '443:443'
    volumes:
      - /data/nginx/data:/data
      - /data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - nas

networks:
  nas:
    external: true
