services:
  app:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    restart: unless-stopped
    ports:
      - '80:80'
      - '82:81'
      - '443:443'
    volumes:
      - /data/nginx/data:/data
      - /data/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - nas
  ddclient:
    image: lscr.io/linuxserver/ddclient:3.11.2
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/nginx/ddclient:/config
    restart: unless-stopped

networks:
  nas:
    external: true
