services:
    sharelatex:
        restart: always
        # Server Pro users:
        # image: quay.io/sharelatex/sharelatex-pro
        image: sharelatex/sharelatex
        networks:
          - nas
          - overleaf
        container_name: sharelatex
        depends_on:
            overleaf_mongo:
                condition: service_healthy
            overleaf_redis:
                condition: service_started
        links:
            - overleaf_mongo
            - overleaf_redis
        stop_grace_period: 60s
        volumes:
            - /data/overleaf/sharelatex_data:/var/lib/overleaf
        labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.overleaf.rule=Host(`overleaf.fgdou.ovh`)'
        - 'traefik.http.routers.overleaf.entryPoints=websecure'
        - 'traefik.http.services.overleaf.loadbalancer.server.port=80'
        environment:
            OVERLEAF_APP_NAME: Fgdou Overleaf
            OVERLEAF_MONGO_URL: mongodb://overleaf_mongo/sharelatex
            # Same property, unfortunately with different names in
            # different locations
            OVERLEAF_REDIS_HOST: overleaf_redis
            REDIS_HOST: overleaf_redis
            ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'
            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'false'
            # temporary fix for LuaLaTex compiles
            # see https://github.com/overleaf/overleaf/issues/695
            TEXMFVAR: /var/lib/overleaf/tmp/texmf-var
            ## Set for SSL via nginx-proxy
            #VIRTUAL_HOST: 103.112.212.22
            OVERLEAF_BEHIND_PROXY: true

            OVERLEAF_SITE_URL: https://overleaf.fgdou.ovh
            OVERLEAF_NAV_TITLE: Fgdou Overleaf
            # OVERLEAF_HEADER_IMAGE_URL: http://example.com/mylogo.png
            OVERLEAF_ADMIN_EMAIL: contact@fgdou.ovh

            # OVERLEAF_LEFT_FOOTER: '[{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            # OVERLEAF_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'

            OVERLEAF_EMAIL_FROM_ADDRESS: "no-reply@fgdou.ovh"

            # OVERLEAF_EMAIL_AWS_SES_ACCESS_KEY_ID:
            # OVERLEAF_EMAIL_AWS_SES_SECRET_KEY:

            OVERLEAF_EMAIL_SMTP_HOST: mail.fgdou.ovh
            OVERLEAF_EMAIL_SMTP_PORT: 587
            OVERLEAF_EMAIL_SMTP_SECURE: false
            OVERLEAF_EMAIL_SMTP_USER: no-reply@fgdou.ovh
            OVERLEAF_EMAIL_SMTP_PASS: ${SMTP_PASSWORD}
            #OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            OVERLEAF_EMAIL_SMTP_IGNORE_TLS: false
            #OVERLEAF_EMAIL_SMTP_NAME: '127.0.0.1'
            #OVERLEAF_EMAIL_SMTP_LOGGER: true
            #OVERLEAF_CUSTOM_EMAIL_FOOTER: "This system is run by department x"

            # ENABLE_CRON_RESOURCE_DELETION: true

            ## Works with test LDAP server shown at bottom of docker compose
            # OVERLEAF_LDAP_URL: 'ldap://ldap:389'
            # OVERLEAF_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
            # OVERLEAF_LDAP_SEARCH_FILTER: '(uid={{username}})'
            # OVERLEAF_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
            # OVERLEAF_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
            # OVERLEAF_LDAP_EMAIL_ATT: 'mail'
            # OVERLEAF_LDAP_NAME_ATT: 'cn'
            # OVERLEAF_LDAP_LAST_NAME_ATT: 'sn'
            # OVERLEAF_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'

            # OVERLEAF_TEMPLATES_USER_ID: "578773160210479700917ee5"
            # OVERLEAF_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"All Templates","url":"/templates/all"}]'


            # OVERLEAF_PROXY_LEARN: "true"

    overleaf_mongo:
        networks:
          - overleaf
        restart: always
        image: bitnami/mongodb:5.0
        container_name: overleaf_mongo
        volumes:
            - /data/overleaf/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
        environment:
          MONGODB_REPLICA_SET_MODE: primary
          ALLOW_EMPTY_PASSWORD: 'yes'

    overleaf_redis:
        restart: always
        networks:
          - overleaf
        image: redis:6.2
        container_name: overleaf_redis
        volumes:
            - /data/overleaf/redis_data:/data

    # ldap:
    #    restart: always
    #    image: rroemhild/test-openldap
    #    container_name: ldap
    #    expose:
    #        - 389
networks:
  nas:
    external: true
  overleaf:
