services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - nas
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${ADMIN_PASSWORD}
      DNSMASQ_LISTENING: all
    volumes:
      - '/data/pihole/pihole:/etc/pihole'
      - '/data/pihole/dnsmasq:/etc/dnsmasq.d'
    restart: unless-stopped
networks:
  nas:
    external: true
