services:
  sr:
    image: ghcr.io/fgdou/sr_project:master
    container_name: sr
    networks:
      - nas
    restart: always
    volumes:
      - /data/sr/leaderboard:/app/leaderboard

networks:
  nas:
    external: true
