services:
  radarr:
    image: lscr.io/linuxserver/radarr:5.7.0
    container_name: radarr
    environment:
      - TZ=Europe/London
    volumes:
      - /films/Radarr:/config
      - /films/Films/films:/movies #optional
      - /films/Films/Download/radarr:/data/downloads #optional
    restart: unless-stopped
    networks:
      - nas
    depends_on:
      - rdtclient
      - prowlarr
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.radarr.rule=Host(`radarr.fgdou.ovh`)'
      - 'traefik.http.routers.radarr.entryPoints=websecure'
      - 'traefik.http.services.radarr.loadbalancer.server.port=7878'
      - 'traefik.http.routers.radarr.middlewares=authentik@docker'

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.6
    container_name: sonarr
    environment:
      - TZ=Europe/London
    volumes:
      - /films/Sonarr:/config
      - /films/Films/series:/tv #optional
      - /films/Films/Download/tv-sonarr:/data/downloads #optional
    restart: unless-stopped
    depends_on:
      - rdtclient
      - prowlarr
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sonarr.rule=Host(`sonarr.fgdou.ovh`)'
      - 'traefik.http.routers.sonarr.entryPoints=websecure'
      - 'traefik.http.services.sonarr.loadbalancer.server.port=8989'
      - 'traefik.http.routers.sonarr.middlewares=authentik@docker'

  rdtclient:
    volumes:
      - /films/Films/Download:/data/downloads
      - /films/rdtclient/:/data/db
    image: rogerfar/rdtclient:2.0.80
    restart: always
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.rdtclient.rule=Host(`rdtclient.fgdou.ovh`)'
      - 'traefik.http.routers.rdtclient.entryPoints=websecure'
      - 'traefik.http.services.rdtclient.loadbalancer.server.port=6500'
      - 'traefik.http.routers.rdtclient.middlewares=authentik@docker'


  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.20.1
    environment:
      - TZ=Europe/Paris
    volumes:
      - /films/prowlarr:/config
    restart: unless-stopped
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prowlarr.rule=Host(`prowlarr.fgdou.ovh`)'
      - 'traefik.http.routers.prowlarr.entryPoints=websecure'
      - 'traefik.http.services.prowlarr.loadbalancer.server.port=9696'
      - 'traefik.http.routers.prowlarr.middlewares=authentik@docker'


  jellyseerr:
    image: fallenbagel/jellyseerr:1.9.2
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    volumes:
      - /films/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - nas
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.fgdou.ovh`)'
      - 'traefik.http.routers.jellyseerr.entryPoints=websecure'
      - 'traefik.http.services.jellyseerr.loadbalancer.server.port=5055'

networks:
  nas:
    external: true
