services:
  radarr:
    image: lscr.io/linuxserver/radarr:5.7.0
    container_name: radarr
    environment:
      - TZ=Europe/London
    volumes:
      - /films/Radarr:/config
      - /films/Films/films:/movies #optional
      - /films/Films/Download/radarr:/data/downloads #optional
    restart: unless-stopped
    networks:
      - nas
    depends_on:
      - rdtclient
      - prowlarr

  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.6
    container_name: sonarr
    environment:
      - TZ=Europe/London
    volumes:
      - /films/Sonarr:/config
      - /films/Films/series:/tv #optional
      - /films/Films/Download/tv-sonarr:/data/downloads #optional
    restart: unless-stopped
    depends_on:
      - rdtclient
      - prowlarr
    networks:
      - nas

  rdtclient:
    volumes:
      - /films/Films/Download:/data/downloads
      - /films/rdtclient/:/data/db
    image: rogerfar/rdtclient:2.0.80
    restart: always
    networks:
      - nas


  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.20.1
    environment:
      - TZ=Europe/Paris
    volumes:
      - /films/prowlarr:/config
    restart: unless-stopped
    networks:
      - nas


  jellyseerr:
    image: fallenbagel/jellyseerr:1.9.2
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    volumes:
      - /films/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - nas

networks:
  nas:
    external: true
