services:

  VaultWarden:
    image: vaultwarden/server:1.30.5
    restart: always
    user: "root:users"
    volumes:
      - /data/VaultWarden:/data/
    environment:
            - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
    networks:
      - nas

networks:
  nas:
    external: true
